<?php
/**
 * Content for the "Bike Rental Location" pages (Rosemary Beach, Seaside,
 * WaterColor, Grayton Beach, Alys Beach, Blue Mountain Beach, ...).
 *
 * One entry per neighborhood, keyed by the page slug. Add more locations
 * here as content briefs come in -- the template
 * (template-bike-rental-location.php) renders whatever is in this array,
 * so a new location never needs a new template file.
 */
function peddlers30a_location_data() {
	return array(

		'bike-rentals-rosemary-beach' => array(
			'title'        => 'Best Bike Rentals in Rosemary Beach | Peddlers 30A',
			'description'  => "Top-rated bike rental for Rosemary Beach, FL. Peddlers 30A is 0.1 miles away with 4.9 stars, 50+ bikes, and 15 years on 30A. Walk in or reserve today.",
			'h1'           => 'Best Bike Rentals in Rosemary Beach, Florida',
			'direct_answer'=> "Peddlers 30A is the top-rated bike rental for Rosemary Beach, 0.1 miles west at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Florida's Panhandle Gulf Coast. With a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A, Peddlers is the closest bicycle rental to Rosemary Beach.",
			'hero_lead'    => "Peddlers 30A is 1 minute west of Rosemary Beach. Walk out and ride into cobblestone lanes, Barrett Square, and Gulf front views.",
			'trust_bar'    => array(
				array( 'heading' => 'FAMILY FIRST', 'sub' => 'All Ages Fit' ),
				array( 'heading' => 'CLOSEST RENTAL', 'sub' => '1 Min Away' ),
				array( 'heading' => 'LOCK INCLUDED', 'sub' => 'Every Rental' ),
				array( 'heading' => 'WALK-IN READY', 'sub' => 'Book or Walk In' ),
				array( 'heading' => 'DELIVERY AVAILABLE', 'sub' => 'Call to Arrange' ),
			),
			'rent_eyebrow' => 'RENT NEAR ROSEMARY',
			'rent_title'   => 'Bikes for Every Rosemary Rider',
			'local_eyebrow'=> 'ROSEMARY BEACH',
			'local_title'  => 'The Village on the Gulf',
			'local_p1'     => "Rosemary Beach is one of 30A's most celebrated communities, built around Barrett Square, a manicured civic green lined with Dutch-Colonial and West Indies architecture, cobblestone lanes, and gas-lit alleyways. More European coastal village than a typical Florida beach vacation town.",
			'local_p2'     => "From Rosemary Beach, Peddlers 30A is one minute west on Scenic Highway 30A. Alys Beach is a 4-minute ride further west. Inlet Beach Regional Access is 6 minutes east. Seagrove and Seaside stretch further west for a full Gulf front day ride.",
			'journey_title'=> "All of 30A From Your Front Doorstep",
			'journey_lead' => "From Rosemary Beach, Scenic Highway 30A stretches east and west along 24 miles of Florida Gulf Coast.",
			'journey_to'   => 'Rosemary Beach',
			'stats'        => array(
				array( 'value' => '1.2 Mi', 'label' => 'EAST' ),
				array( 'value' => '8.3 Mi', 'label' => 'WEST' ),
				array( 'value' => '24 Miles', 'label' => 'MILES OF 30A' ),
				array( 'value' => '16+', 'label' => 'DESTINATIONS' ),
			),
			'callout'      => "Peddlers 30A is 0.1 miles west of Rosemary Beach at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Scenic Highway 30A.",
			'pavilion_eyebrow' => 'YOUR HOME BASE',
			'pavilion_title'   => 'Where Every Rosemary Beach Ride Begins on 30A',
			'pavilion_lead'    => "Peddlers is one minute west in Seacrest Beach. Coffee at Kickstand Coffee before heading out, bikes at the door, and live music and cocktails waiting when you return from Rosemary Beach.",
			'categories'   => array(
				array( 'num' => '01', 'label' => 'CLASSIC CRUISERS', 'title' => 'Start at Barrett Square', 'copy' => "Classic cruiser bikes handle the flat, paved ride between Rosemary Beach, Alys Beach at 4 minutes west, and Inlet Beach at 6 minutes east. Perfect for a beach vacation day ride." ),
				array( 'num' => '02', 'label' => 'MULTI-SPEED BIKES', 'title' => 'Cover the Full Coastline', 'copy' => "Seagrove Beach is 36 minutes west of Rosemary Beach and Seaside is 39. Multi-speed gearing makes the longer Gulf front runs genuinely comfortable." ),
				array( 'num' => '03', 'label' => 'KIDS & FAMILY', 'title' => 'Start Pedalling Together', 'copy' => "Rosemary Beach and Alys Beach are natural first rides for families. Peddlers has cruiser bikes, kids' bikes, tag-alongs, and trailers for every age." ),
				array( 'num' => '04', 'label' => 'SPECIALTY', 'title' => 'Explore Beyond the Village', 'copy' => "Tandems and specialty bikes for Rosemary Beach riders wanting to go further, west to Seagrove or east to Inlet Beach and Camp Helen State Park." ),
			),
			'why_eyebrow'  => 'THE SERVICE STANDARD',
			'why_title'    => 'Why Peddlers Is the Best Bike Rental Near Rosemary Beach',
			'why_cards'    => array(
				array( 'title' => 'Right Next Door', 'copy' => "No driving, no loading bikes. Peddlers is one minute west of Rosemary Beach, and 30A is right out the door the moment you pick up your bike." ),
				array( 'title' => 'Inspected Every Day', 'copy' => "Every bike is checked before it goes out. The closest bicycle rental to Rosemary Beach is also the best-maintained fleet on Scenic Highway 30A." ),
				array( 'title' => 'Delivery Service Available', 'copy' => "Staying in Rosemary Beach and prefer to start from your rental? Peddlers offers a delivery service to Rosemary Beach properties. Contact us to arrange." ),
				array( 'title' => 'Local Advice Included', 'copy' => "Ask the team which direction suits your group, where Barrett Square is by bike, and which ride fits your plan for the day." ),
			),
			'closing_title'=> 'Your Rosemary Beach Ride Starts Here',
			'beaches_lead' => "From Rosemary Beach, Alys Beach is 4 minutes west and Inlet Beach is 6 minutes east. Seagrove Beach and Seaside stretch further west for a longer day on 30A.",
			'beaches'      => array(
				array( 'badge' => '4 MIN RIDE', 'name' => 'Alys Beach', 'tag' => 'White Walls, Quiet Courtyards', 'copy' => "Alys Beach is a 4-minute ride west from Rosemary Beach. Stark white Bermudan architecture, quiet pedestrian lanes, and a stop at Fonville Press for cold brew mid-ride.", 'pills' => array( '4 Min West', 'Easy Ride', 'Beach Access' ), 'slug' => 'bike-rentals-alys-beach' ),
				array( 'badge' => '6 MIN RIDE', 'name' => 'Inlet Beach', 'tag' => 'Eastern End of 30A', 'copy' => "Inlet Beach is 6 minutes east of Rosemary Beach. Walton County's largest public beach access with boardwalk ramps, restrooms, and seasonal lifeguards on the Gulf.", 'pills' => array( '6 Min East', 'Public Access', 'Beach Access' ), 'slug' => 'bike-rentals-inlet-beach' ),
				array( 'badge' => '36 MIN RIDE', 'name' => 'Seagrove Beach', 'tag' => 'Old Florida, Quiet Roads', 'copy' => "Seagrove Beach is 36 minutes west of Rosemary Beach. One of 30A's oldest communities with oak canopy shade, beach cottages, and the most local feel on the coast.", 'pills' => array( '36 Min West', 'Local Feel', 'Beach Access' ), 'slug' => 'bike-rentals-seagrove-beach' ),
				array( 'badge' => '39 MIN RIDE', 'name' => 'Seaside', 'tag' => 'The Town Everyone Knows', 'copy' => "Seaside is 39 minutes west from Rosemary Beach. Lock up at the amphitheater, walk Central Square on foot, and grab lunch at the Airstream food row before heading back.", 'pills' => array( '39 Min West', 'Town Square', 'Shops & Food' ), 'slug' => 'bike-rentals-seaside' ),
				array( 'badge' => '~42 MIN RIDE', 'name' => 'WaterColor', 'tag' => 'Resort Coast, Western 30A', 'copy' => "WaterColor is approximately 42 minutes west of Rosemary Beach. Cross the timber bridge over Western Lake and stop at WaterColor Town Center for lunch or a drink along the water.", 'pills' => array( '~42 Min West', 'Gulf Views', 'Resort Stop' ), 'slug' => 'bike-rentals-watercolor' ),
			),
			'testimonials_title' => 'Stories From Rosemary Beach',
			'faq_title'    => 'What to Know First',
			'faqs'         => array(
				array( 'q' => 'Where is Peddlers 30A located near Rosemary Beach?', 'a' => "Peddlers 30A is 0.1 miles west of Rosemary Beach at 10343 E County Hwy 30A, Inlet Beach, FL 32461 in the Seacrest Beach community. It is the closest bike rental in Rosemary Beach FL, one minute west on Scenic Highway 30A." ),
				array( 'q' => 'Does Rosemary Beach have public beach access?', 'a' => "Rosemary Beach has private deeded walkovers for registered homeowners and guests only. The nearest public beach access is Inlet Beach Regional Access, 1.2 miles east, about 6 minutes by bike, with boardwalk ramps, restrooms, and seasonal lifeguards." ),
				array( 'q' => 'Can I walk in for a bike rental near Rosemary Beach?', 'a' => "Yes. Peddlers is one minute west of Rosemary Beach and walk-ins are welcome. During peak summer weekends, the fleet fills quickly, so booking ahead is recommended. Weekdays and off-season, walk-in availability is generally good." ),
				array( 'q' => 'Do you deliver bikes to Rosemary Beach rental properties?', 'a' => "Yes, Peddlers delivers bikes to Rosemary Beach rental properties. Contact us to arrange your delivery and confirm availability for your dates. Starting your 30A bicycle rental from your front door is the easiest option." ),
				array( 'q' => 'What bikes work best for riding from Rosemary Beach?', 'a' => "Classic cruiser bikes are perfect for short rides between Rosemary Beach, Alys Beach, and Inlet Beach. For longer rides west to Seagrove or Seaside, a 7-speed multi-speed bike is more comfortable on the 36 to 39-minute runs." ),
				array( 'q' => 'What are the best 30A bike rides starting from Rosemary Beach?', 'a' => "The best 30A bike rentals near Rosemary Beach lead to Alys Beach at 4 minutes west and Inlet Beach at 6 minutes east. For a longer day, Seagrove Beach is 36 minutes west and Seaside is 39 minutes west along the Florida Gulf front." ),
				array( 'q' => 'Is Peddlers the top-rated bike rental near Rosemary Beach?', 'a' => "Yes. Peddlers 30A is the closest and top-rated bike rental to Rosemary Beach with a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A. It is 0.1 miles west, one minute away in Seacrest Beach." ),
			),
		),

		'bike-rentals-seaside' => array(
			'title'        => 'Best Bike Rentals in Seaside FL | Peddlers 30A',
			'description'  => "Top-rated bike rental for Seaside FL. Peddlers 30A is 42 minutes east with 4.9 stars, 50+ bikes, and 15 years on 30A. Deliver to your door or reserve today.",
			'h1'           => 'Best Bike Rentals in Seaside, Florida',
			'direct_answer'=> "Peddlers 30A is the top-rated bike rental for Seaside, 8.3 miles east at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Florida's Panhandle Gulf Coast. With a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A, Peddlers is the closest dedicated bicycle rental for a Seaside FL beach vacation day.",
			'hero_lead'    => "Peddlers 30A is 42 minutes east of Seaside on Scenic Highway 30A. Reserve online or call ahead. Delivery to Seaside FL is available.",
			'trust_bar'    => array(
				array( 'heading' => 'FAMILY FIRST', 'sub' => 'All Ages Fit' ),
				array( 'heading' => 'DELIVERY AVAILABLE', 'sub' => 'Call to Arrange' ),
				array( 'heading' => 'LOCK INCLUDED', 'sub' => 'Every Rental' ),
				array( 'heading' => 'WALK-IN READY', 'sub' => 'Book or Walk In' ),
				array( 'heading' => '42 MIN EAST', 'sub' => 'Pickup or Deliver' ),
			),
			'rent_eyebrow' => 'RENT NEAR SEASIDE',
			'rent_title'   => 'Bikes for Every Seaside Rider',
			'local_eyebrow'=> 'SEASIDE ON 30A',
			'local_title'  => 'The Town That Started It All',
			'local_p1'     => "Seaside is the birthplace of New Urbanism and the real-life filming location of The Truman Show. Central Square is framed by pastel cottages, an open-air amphitheater, and Airstream Row, where retro food trailers serve lunch to cyclists locked at the perimeter racks.",
			'local_p2'     => "From Seaside, Peddlers 30A is 42 minutes east on Scenic Highway 30A. WaterColor is 3 minutes west and Seagrove Beach is 8 minutes east. Seaside sits at the center of 30A's Gulf front, making it the natural midpoint for a full beach vacation day ride.",
			'journey_title'=> "30A Stretches Both Ways From Seaside",
			'journey_lead' => "From Seaside, Scenic Highway 30A stretches east toward Seagrove and west toward Grayton Beach and the Gulf front.",
			'journey_to'   => 'Seaside',
			'stats'        => array(
				array( 'value' => '1.5 Mi', 'label' => 'EAST' ),
				array( 'value' => '3.1 Mi', 'label' => 'WEST' ),
				array( 'value' => '24 Miles', 'label' => 'MILES OF 30A' ),
				array( 'value' => '16+', 'label' => 'DESTINATIONS' ),
			),
			'callout'      => "Peddlers 30A is 8.3 miles east of Seaside at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Scenic Highway 30A.",
			'pavilion_eyebrow' => 'YOUR HOME BASE',
			'pavilion_title'   => 'Where Every Seaside Ride Begins on 30A',
			'pavilion_lead'    => "Peddlers is 42 minutes east in Seacrest Beach. Reserve online or call ahead, and Kickstand Coffee is waiting when you arrive. Bikes are ready at the door for your full day in Seaside.",
			'categories'   => array(
				array( 'num' => '01', 'label' => 'CLASSIC CRUISERS', 'title' => 'Cruise Into Seaside', 'copy' => "Cruiser bikes handle the flat Gulf front path into Seaside. Lock up at Central Square perimeter racks, explore on foot, and stop at Airstream Row." ),
				array( 'num' => '02', 'label' => 'MULTI-SPEED BIKES', 'title' => 'Ride the Full 42 Minutes', 'copy' => "The 42-minute ride from Peddlers to Seaside is most comfortable on a 7-speed daily rental bike. Multi-speed gearing handles the full Gulf front run." ),
				array( 'num' => '03', 'label' => 'KIDS & FAMILY', 'title' => 'Family Day in Seaside', 'copy' => "Seaside's Central Square and Airstream Row are ideal for a family beach vacation day. Peddlers has kids' bikes, tag-alongs, and trailers for every rider." ),
				array( 'num' => '04', 'label' => 'SPECIALTY', 'title' => 'Cover All of Western 30A', 'copy' => "Tandems and specialty bikes for Seaside riders continuing west to Grayton Beach (15 min) or east to Prominence (24 min) and beyond on 30A." ),
			),
			'why_eyebrow'  => 'THE SERVICE STANDARD',
			'why_title'    => 'Why Peddlers Is the Best Bike Rental Near Seaside 30A',
			'why_cards'    => array(
				array( 'title' => 'Delivery to Seaside', 'copy' => "Let Peddlers come to you. Delivery to Seaside FL rental properties is available. Contact us to arrange your bicycle rental drop-off and start from your front door." ),
				array( 'title' => 'Inspected Every Day', 'copy' => "Every bike goes out inspected and tuned. The best-maintained fleet on Scenic Highway 30A is 42 minutes east of Seaside at Peddlers Pavilion." ),
				array( 'title' => 'Delivery Service Available', 'copy' => "Prefer to start the day from your Seaside rental property? Peddlers delivers. Contact us to arrange your delivery service to Seaside 30A." ),
				array( 'title' => 'Local Advice Included', 'copy' => "Ask the team about the Seaside perimeter bike racks, the best Gulf front approach from the east, and which bike suits your group's plan for the day." ),
			),
			'closing_title'=> 'Your Seaside 30A Ride Starts Here',
			'beaches_lead' => "From Seaside, WaterColor is 3 minutes west and Seagrove Beach is 8 minutes east. Grayton Beach is 15 minutes west and Prominence is 24 minutes east along the Gulf front.",
			'beaches'      => array(
				array( 'badge' => '3 MIN RIDE', 'name' => 'WaterColor', 'tag' => 'Gulf Views and Timber Bridges', 'copy' => "WaterColor is 3 minutes west of Seaside. Cross the Western Lake timber bridge on the path and stop at WaterColor Town Center for coffee or a mid-ride drink.", 'pills' => array( '3 Min West', 'Gulf Views', 'Resort Stop' ), 'slug' => 'bike-rentals-watercolor' ),
				array( 'badge' => '8 MIN RIDE', 'name' => 'Seagrove Beach', 'tag' => 'Old Florida, Quiet Roads', 'copy' => "Seagrove Beach is 8 minutes east of Seaside. One of 30A's oldest communities, with maritime oak canopy, quiet cottage lanes, and a relaxed local feel.", 'pills' => array( '8 Min East', 'Local Feel', 'Beach Access' ), 'slug' => 'bike-rentals-seagrove-beach' ),
				array( 'badge' => '15 MIN RIDE', 'name' => 'Grayton Beach', 'tag' => 'Old Florida, Untouched', 'copy' => "Grayton Beach is 15 minutes west of Seaside. The Red Bar for live music, Grayton Beach State Park, and 30A's most bohemian, unplanned community character.", 'pills' => array( '15 Min West', 'State Park', 'Live Music' ), 'slug' => 'bike-rentals-grayton-beach' ),
				array( 'badge' => '24 MIN RIDE', 'name' => 'Prominence', 'tag' => "30A's Most Lively Hub", 'copy' => "Prominence is 24 minutes east of Seaside. The Big Chill outdoor amphitheater has a 25-foot LED screen, live music, food hall dining, and craft drinks nightly.", 'pills' => array( '24 Min East', 'Live Events', 'Food & Drinks' ), 'slug' => 'bike-rentals-prominence' ),
				array( 'badge' => '~25 MIN RIDE', 'name' => 'Blue Mountain Beach', 'tag' => "Florida's Highest Gulf Point", 'copy' => "Blue Mountain Beach is approximately 25 minutes west of Seaside. The highest elevation on Florida's Gulf Coast, with Big Redfish Lake and Blue Mountain Bakery on the path.", 'pills' => array( '~25 Min West', 'Highest Point', 'Beach Access' ), 'slug' => 'bike-rentals-blue-mountain-beach' ),
			),
			'testimonials_title' => 'Stories From Seaside FL',
			'faq_title'    => 'What to Know First',
			'faqs'         => array(
				array( 'q' => 'Where is Peddlers 30A located near Seaside FL?', 'a' => "Peddlers 30A is 8.3 miles east of Seaside at 10343 E County Hwy 30A, Inlet Beach, FL 32461 in the Seacrest Beach community. It is the closest bike rental to Seaside FL, 42 minutes east on Scenic Highway 30A toward Seagrove and Prominence." ),
				array( 'q' => 'Does Seaside have public beach access?', 'a' => "Seaside's beach pavilions require wristbands for registered homeowners and guests. The nearest public beach access is Van Ness Butler Jr. Regional Access on the Seaside and Seagrove border, with bike racks, restrooms, and Gulf access for all visitors." ),
				array( 'q' => 'Can I walk in for a bike rental near Seaside FL?', 'a' => "Peddlers is 42 minutes east of Seaside on Scenic Highway 30A. Walk-ins are welcome at the Pavilion. For Seaside visitors, calling ahead or reserving online is recommended so your bikes are ready for the full day when you arrive." ),
				array( 'q' => 'Do you deliver bikes to Seaside 30A?', 'a' => "Yes, Peddlers delivers bikes to Seaside FL rental properties. Contact us to arrange your delivery and confirm availability for your dates. Starting your 30A bicycle rental from your Seaside front door is the most convenient option for the day." ),
				array( 'q' => 'What bikes work best for riding to and from Seaside?', 'a' => "Multi-speed bikes are the best choice for the 42-minute daily rental ride between Peddlers and Seaside. Cruiser bikes are ideal once you arrive, for riding between Seaside, WaterColor (3 min west), and Seagrove Beach (8 min east) on the flat Gulf front path." ),
				array( 'q' => 'What are the best 30A bike rides starting from Seaside FL?', 'a' => "The best 30A bike rentals near Seaside connect you to WaterColor in 3 minutes west and Seagrove Beach in 8 minutes east. For a longer beach vacation ride, Grayton Beach is 15 minutes west and Prominence is 24 minutes east on Scenic Highway 30A." ),
				array( 'q' => 'Is Peddlers the top-rated bike rental near Seaside 30A?', 'a' => "Yes. Peddlers 30A is the top-rated bike rental for Seaside with a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A. It is 8.3 miles east of Seaside in the Seacrest Beach community on Florida's Panhandle Gulf Coast." ),
			),
		),

		'bike-rentals-watercolor' => array(
			'title'        => 'Best Bike Rentals in WaterColor FL | Peddlers 30A',
			'description'  => "Top-rated bike rental for WaterColor FL. Peddlers 30A is 44 minutes east with 4.9 stars, 50+ bikes, and 15 years on 30A. Deliver to your door or reserve today.",
			'h1'           => 'Best Bike Rentals in WaterColor, Florida',
			'direct_answer'=> "Peddlers 30A is the top-rated bike rental for WaterColor, 8.8 miles east at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Florida's Panhandle Gulf Coast. With a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A, Peddlers is the closest dedicated bicycle rental for a WaterColor FL beach vacation.",
			'hero_lead'    => "Peddlers 30A is 44 minutes east of WaterColor on Scenic Highway 30A. Reserve online or call ahead. Delivery to WaterColor FL is available.",
			'trust_bar'    => array(
				array( 'heading' => 'FAMILY FIRST', 'sub' => 'All Ages Fit' ),
				array( 'heading' => 'DELIVERY AVAILABLE', 'sub' => 'Call to Arrange' ),
				array( 'heading' => 'LOCK INCLUDED', 'sub' => 'Every Rental' ),
				array( 'heading' => 'WALK-IN READY', 'sub' => 'Book or Walk In' ),
				array( 'heading' => '44 MIN EAST', 'sub' => 'Pickup or Deliver' ),
			),
			'rent_eyebrow' => 'RENT NEAR WATERCOLOR',
			'rent_title'   => 'Bikes for Every WaterColor Rider',
			'local_eyebrow'=> 'WATERCOLOR',
			'local_title'  => 'Where Luxury Meets the Trail',
			'local_p1'     => "WaterColor is a 500-acre resort community on 30A's Gulf front. Cyclists arriving from the east cross the timber bridge over Western Lake, the most famous coastal dune lake on 30A. WaterColor Town Center faces Seaside to the east and anchors the public side of the resort.",
			'local_p2'     => "From WaterColor, Seaside is 3 minutes east and Peddlers 30A is 44 minutes east on Scenic Highway 30A. Seagrove Beach is 10 minutes east. Grayton Beach is 13 minutes west and Blue Mountain Beach is 20 minutes west on the Gulf front.",
			'journey_title'=> "WaterColor Sits at the Heart of 30A",
			'journey_lead' => "From WaterColor, 30A stretches east to Seaside and west to Grayton Beach across 24 miles of Florida Gulf Coast.",
			'journey_to'   => 'WaterColor',
			'stats'        => array(
				array( 'value' => '0.5 Mi', 'label' => 'EAST' ),
				array( 'value' => '2.6 Mi', 'label' => 'WEST' ),
				array( 'value' => '24 Miles', 'label' => 'MILES OF 30A' ),
				array( 'value' => '16+', 'label' => 'DESTINATIONS' ),
			),
			'callout'      => "Peddlers 30A is 8.8 miles east of WaterColor at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Scenic Highway 30A.",
			'pavilion_eyebrow' => 'YOUR HOME BASE',
			'pavilion_title'   => 'Where Every WaterColor Ride Begins on 30A',
			'pavilion_lead'    => "Peddlers is 44 minutes east in Seacrest Beach. Reserve online or call ahead, and Kickstand Coffee is waiting when you arrive. Bikes are ready at the door for your WaterColor day on 30A.",
			'categories'   => array(
				array( 'num' => '01', 'label' => 'CLASSIC CRUISERS', 'title' => 'Ride Into WaterColor', 'copy' => "Cruiser bikes handle the flat Gulf front path into WaterColor. Seaside is just 3 minutes east and Seagrove Beach is 10 minutes east for a longer day." ),
				array( 'num' => '02', 'label' => 'MULTI-SPEED BIKES', 'title' => 'Ride the Full 44 Minutes', 'copy' => "The 44-minute ride from Peddlers to WaterColor is most comfortable on a 7-speed daily rental bike. Multi-speed gearing handles the full Gulf front run." ),
				array( 'num' => '03', 'label' => 'KIDS & FAMILY', 'title' => 'Family Day at WaterColor', 'copy' => "WaterColor's paved internal paths and Cerulean Park are ideal for family riders. Peddlers has kids' bikes, tag-alongs, and trailers for every rider in your group." ),
				array( 'num' => '04', 'label' => 'SPECIALTY', 'title' => 'Head West Toward Grayton', 'copy' => "Tandems and specialty bikes for WaterColor riders heading west to Grayton Beach (13 min) or east to Seagrove Beach (10 min) and beyond on 30A." ),
			),
			'why_eyebrow'  => 'THE SERVICE STANDARD',
			'why_title'    => 'Why Peddlers Is the Best Bike Rental Near WaterColor FL',
			'why_cards'    => array(
				array( 'title' => 'Delivery to WaterColor', 'copy' => "Let Peddlers come to you. Delivery to WaterColor FL rental properties is available. Contact us to arrange your bicycle rental drop-off and start the day from your front door." ),
				array( 'title' => 'Inspected Every Day', 'copy' => "Every bike goes out inspected and tuned. The best-maintained fleet on Scenic Highway 30A is 44 minutes east of WaterColor at Peddlers Pavilion." ),
				array( 'title' => 'Delivery Service Available', 'copy' => "Prefer to start from your WaterColor rental? Peddlers delivers. Contact us to arrange your delivery service to WaterColor Florida." ),
				array( 'title' => 'Local Advice Included', 'copy' => "Ask the team about the WaterColor timber bridge route, the best approach from Town Center, and which bike fits your group's plan for the day on 30A." ),
			),
			'closing_title'=> 'Your WaterColor 30A Ride Starts Here',
			'beaches_lead' => "From WaterColor, Seaside is 3 minutes east and Seagrove Beach is 10 minutes east. Grayton Beach is 13 minutes west and Blue Mountain Beach is 20 minutes west.",
			'beaches'      => array(
				array( 'badge' => '3 MIN RIDE', 'name' => 'Seaside', 'tag' => 'The Town Everyone Knows', 'copy' => "Seaside is 3 minutes east of WaterColor. Lock up at Central Square perimeter racks, explore the amphitheater on foot, and stop at the Airstream food row for lunch.", 'pills' => array( '3 Min East', 'Town Square', 'Shops & Food' ), 'slug' => 'bike-rentals-seaside' ),
				array( 'badge' => '10 MIN RIDE', 'name' => 'Seagrove Beach', 'tag' => 'Old Florida, Quiet Roads', 'copy' => "Seagrove Beach is 10 minutes east of WaterColor. One of 30A's oldest communities, with maritime oak canopy, classic beach cottages, and a relaxed local feel.", 'pills' => array( '10 Min East', 'Local Feel', 'Beach Access' ), 'slug' => 'bike-rentals-seagrove-beach' ),
				array( 'badge' => '13 MIN RIDE', 'name' => 'Grayton Beach', 'tag' => 'Old Florida, Untouched', 'copy' => "Grayton Beach is 13 minutes west of WaterColor. The Red Bar for live music and Grayton Beach State Park make it the most bohemian stop on western 30A.", 'pills' => array( '13 Min West', 'State Park', 'Live Music' ), 'slug' => 'bike-rentals-grayton-beach' ),
				array( 'badge' => '20 MIN RIDE', 'name' => 'Blue Mountain Beach', 'tag' => "Florida's Highest Gulf Point", 'copy' => "Blue Mountain Beach is 20 minutes west of WaterColor. The highest elevation on Florida's Gulf Coast, with Big Redfish Lake and Blue Mountain Bakery along the path.", 'pills' => array( '20 Min West', 'Highest Point', 'Beach Access' ), 'slug' => 'bike-rentals-blue-mountain-beach' ),
				array( 'badge' => '~27 MIN RIDE', 'name' => 'Prominence', 'tag' => "30A's Most Lively Hub", 'copy' => "Prominence is approximately 27 minutes east of WaterColor. The Big Chill outdoor amphitheater has a 25-foot LED screen, live music, and food hall dining nightly.", 'pills' => array( '~27 Min East', 'Live Events', 'Food & Drinks' ), 'slug' => 'bike-rentals-prominence' ),
			),
			'testimonials_title' => 'Stories From WaterColor FL',
			'faq_title'    => 'What to Know First',
			'faqs'         => array(
				array( 'q' => 'Where is Peddlers 30A located near WaterColor FL?', 'a' => "Peddlers 30A is 8.8 miles east of WaterColor at 10343 E County Hwy 30A, Inlet Beach, FL 32461 in the Seacrest Beach community. It is the closest bike rental to WaterColor FL, 44 minutes east on Scenic Highway 30A." ),
				array( 'q' => 'Does WaterColor have public beach access?', 'a' => "WaterColor Beach Club access requires verified wristbands for registered homeowners and resort guests only. The nearest public beach access is Van Ness Butler Jr. Regional Access on the Seaside and Seagrove border, 3 minutes east of WaterColor." ),
				array( 'q' => 'What is Western Lake near WaterColor on 30A?', 'a' => "Western Lake is 30A's most famous coastal dune lake and borders WaterColor directly. Cyclists cross it via the timber bridge on the paved path along Scenic Highway 30A. The WaterColor Boathouse offers paddleboard and kayak rentals on the lake." ),
				array( 'q' => 'Do you deliver bikes to WaterColor FL?', 'a' => "Yes, Peddlers delivers bikes to WaterColor rental properties. Contact us to arrange your delivery and confirm availability for your dates. Starting your 30A bicycle rental from your WaterColor front door is the most convenient option." ),
				array( 'q' => 'What bikes work best for riding to and from WaterColor?', 'a' => "Multi-speed bikes are the best daily rental choice for the 44-minute ride between Peddlers and WaterColor. Cruiser bikes are ideal for shorter Gulf front rides once you arrive, between WaterColor, Seaside (3 min east), and Seagrove Beach (10 min east)." ),
				array( 'q' => 'What are the best 30A bike rides starting from WaterColor FL?', 'a' => "The best 30A bike rentals near WaterColor connect you to Seaside in 3 minutes east and Seagrove Beach in 10 minutes east. For a longer beach vacation ride, Grayton Beach is 13 minutes west and Blue Mountain Beach is 20 minutes west on the Gulf front." ),
				array( 'q' => 'Is Peddlers the top-rated bike rental near WaterColor FL?', 'a' => "Yes. Peddlers 30A is the top-rated bike rental for WaterColor with a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A. It is 8.8 miles east of WaterColor in the Seacrest Beach community on Florida's Panhandle Gulf Coast." ),
			),
		),

		'bike-rentals-grayton-beach' => array(
			'title'        => 'Best Bike Rentals in Grayton Beach | Peddlers 30A',
			'description'  => "Top-rated bike rental for Grayton Beach FL. Peddlers 30A is 58 minutes east with 4.9 stars, 50+ bikes, and 15 years on 30A. Deliver to your door or reserve today.",
			'h1'           => 'Best Bike Rentals in Grayton Beach, Florida',
			'direct_answer'=> "Peddlers 30A is the top-rated bike rental for Grayton Beach, 11.5 miles east at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Florida's Panhandle Gulf Coast. With a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A, Peddlers is the closest dedicated bicycle rental for a Grayton Beach FL beach vacation.",
			'hero_lead'    => "Peddlers 30A is 58 minutes east of Grayton Beach on Scenic Highway 30A. Reserve ahead or call. Delivery to Grayton Beach FL is available.",
			'trust_bar'    => array(
				array( 'heading' => 'FAMILY FIRST', 'sub' => 'All Ages Fit' ),
				array( 'heading' => 'DELIVERY AVAILABLE', 'sub' => 'Call to Arrange' ),
				array( 'heading' => 'LOCK INCLUDED', 'sub' => 'Every Rental' ),
				array( 'heading' => 'WALK-IN READY', 'sub' => 'Book or Walk In' ),
				array( 'heading' => '58 MIN EAST', 'sub' => 'Pickup or Deliver' ),
			),
			'rent_eyebrow' => 'RENT NEAR GRAYTON BEACH',
			'rent_title'   => 'Bikes for Every Grayton Rider',
			'local_eyebrow'=> 'GRAYTON BEACH',
			'local_title'  => 'The Original Spirit of 30A',
			'local_p1'     => "Grayton Beach is 30A's most original community, known for its motto: Nice Dogs, Strange People. The Red Bar anchors the village with nightly jazz and funk bands, legendary crab cakes, and a bohemian interior that has been a 30A institution for decades.",
			'local_p2'     => "From Grayton Beach, Peddlers 30A is 58 minutes east on Scenic Highway 30A. Blue Mountain Beach is 10 minutes west and WaterColor is 13 minutes east. Grayton Beach State Park borders the community with 2,000 acres of Gulf beach and coastal dune lakes.",
			'journey_title'=> "30A Stretches Both Ways From Grayton",
			'journey_lead' => "From Grayton Beach, 30A stretches east to WaterColor and west to Blue Mountain Beach on Florida's Gulf Coast.",
			'journey_to'   => 'Grayton Beach',
			'stats'        => array(
				array( 'value' => '2.6 Mi', 'label' => 'EAST' ),
				array( 'value' => '2.0 Mi', 'label' => 'WEST' ),
				array( 'value' => '24 Miles', 'label' => 'MILES OF 30A' ),
				array( 'value' => '16+', 'label' => 'DESTINATIONS' ),
			),
			'callout'      => "Peddlers 30A is 11.5 miles east of Grayton Beach at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Scenic Highway 30A.",
			'pavilion_eyebrow' => 'YOUR HOME BASE',
			'pavilion_title'   => 'Where Every Grayton Beach Ride Begins',
			'pavilion_lead'    => "Peddlers is 58 minutes east in Seacrest Beach. Reserve online or call ahead, and Kickstand Coffee is waiting on arrival. Bikes are ready at the door for your full day at Grayton Beach.",
			'categories'   => array(
				array( 'num' => '01', 'label' => 'CLASSIC CRUISERS', 'title' => 'Cruise Into Grayton Beach', 'copy' => "Cruiser bikes handle the flat Gulf front path into Grayton Beach. WaterColor is 13 minutes east and Seaside is 15 minutes east for a longer day ride." ),
				array( 'num' => '02', 'label' => 'MULTI-SPEED BIKES', 'title' => 'Ride the Full 58 Minutes', 'copy' => "The 58-minute ride from Peddlers to Grayton Beach is a serious Gulf front run. A 7-speed daily rental bike makes the full ride comfortable both ways." ),
				array( 'num' => '03', 'label' => 'KIDS & FAMILY', 'title' => 'Explore the Village Paths', 'copy' => "Grayton Beach's quiet side streets and the state park boardwalk approach are ideal for families. Peddlers has kids' bikes, tag-alongs, and trailers." ),
				array( 'num' => '04', 'label' => 'SPECIALTY', 'title' => 'Go West to Gulf Place', 'copy' => "Tandems and specialty bikes for Grayton Beach riders heading west to Gulf Place (27 min) or east to WaterColor (13 min) and Seaside (15 min) on 30A." ),
			),
			'why_eyebrow'  => 'THE SERVICE STANDARD',
			'why_title'    => 'Why Peddlers Is the Best Bike Rental Near Grayton Beach',
			'why_cards'    => array(
				array( 'title' => 'Delivery to Grayton Beach', 'copy' => "Let Peddlers come to you. Delivery to Grayton Beach FL rental properties is available. Contact us to arrange your bicycle rental drop-off and start the day from your front door." ),
				array( 'title' => 'Inspected Every Day', 'copy' => "Every bike goes out inspected and tuned. The best-maintained fleet on Scenic Highway 30A is 58 minutes east of Grayton Beach at Peddlers Pavilion." ),
				array( 'title' => 'Delivery Service Available', 'copy' => "Prefer to start from your Grayton Beach rental? Peddlers delivers. Contact us to arrange your delivery service to Grayton Beach on 30A." ),
				array( 'title' => 'Local Advice Included', 'copy' => "Ask the team about the Grayton Beach State Park approach by bike, the best Gulf front path in, and which bike fits your group's full day on 30A." ),
			),
			'closing_title'=> 'Your Grayton Beach Ride Starts Here',
			'beaches_lead' => "From Grayton Beach, Blue Mountain Beach is 10 minutes west and WaterColor is 13 minutes east. Seaside is 15 minutes east and Gulf Place is 27 minutes west along the Gulf front.",
			'beaches'      => array(
				array( 'badge' => '10 MIN RIDE', 'name' => 'Blue Mountain Beach', 'tag' => "Florida's Highest Gulf Point", 'copy' => "Blue Mountain Beach is 10 minutes west of Grayton Beach. The highest elevation on Florida's Gulf Coast, with Big Redfish Lake and Blue Mountain Bakery right on the path.", 'pills' => array( '10 Min West', 'Highest Point', 'Beach Access' ), 'slug' => 'bike-rentals-blue-mountain-beach' ),
				array( 'badge' => '13 MIN RIDE', 'name' => 'WaterColor', 'tag' => 'Gulf Views and Timber Bridges', 'copy' => "WaterColor is 13 minutes east of Grayton Beach. Cross the Western Lake timber bridge on the path and stop at WaterColor Town Center for a mid-ride break.", 'pills' => array( '13 Min East', 'Gulf Views', 'Resort Stop' ), 'slug' => 'bike-rentals-watercolor' ),
				array( 'badge' => '15 MIN RIDE', 'name' => 'Seaside', 'tag' => 'The Town Everyone Knows', 'copy' => "Seaside is 15 minutes east of Grayton Beach. Lock up at Central Square perimeter racks, explore the amphitheater on foot, and stop at Airstream Row for lunch.", 'pills' => array( '15 Min East', 'Town Square', 'Shops & Food' ), 'slug' => 'bike-rentals-seaside' ),
				array( 'badge' => '27 MIN RIDE', 'name' => 'Gulf Place', 'tag' => 'The Heartbeat of Western 30A', 'copy' => "Gulf Place is 27 minutes west of Grayton Beach. Shunk Gulley oyster bar, daily live music, and Ed Walline Regional Beach Access directly across 30A from the town center.", 'pills' => array( '27 Min West', 'Live Events', 'Beach Access' ), 'slug' => 'bike-rentals-gulf-place' ),
				array( 'badge' => '~23 MIN RIDE', 'name' => 'Seagrove Beach', 'tag' => 'Old Florida, Quiet Roads', 'copy' => "Seagrove Beach is approximately 23 minutes east of Grayton Beach via Seaside. One of 30A's oldest communities, with oak canopy shade and a quiet local feel.", 'pills' => array( '~23 Min East', 'Local Feel', 'Beach Access' ), 'slug' => 'bike-rentals-seagrove-beach' ),
			),
			'testimonials_title' => 'Stories From Grayton Beach FL',
			'faq_title'    => 'What to Know First',
			'faqs'         => array(
				array( 'q' => 'Where is Peddlers 30A located near Grayton Beach?', 'a' => "Peddlers 30A is 11.5 miles east of Grayton Beach at 10343 E County Hwy 30A, Inlet Beach, FL 32461 in the Seacrest Beach community. It is the closest bike rental to Grayton Beach FL, 58 minutes east on Scenic Highway 30A." ),
				array( 'q' => 'What is The Red Bar in Grayton Beach?', 'a' => "The Red Bar is the most famous landmark in Grayton Beach — a legendary dive-style restaurant, bar, and live music venue known for nightly jazz and funk bands, world-class crab cakes, and a bohemian interior that has defined the 30A community for decades." ),
				array( 'q' => 'Can I visit Grayton Beach State Park by bike?', 'a' => "Yes. Grayton Beach State Park is directly accessible by bike from the 30A path. The park covers 2,000 acres with pristine Gulf beaches and coastal dune lakes. Entry is $2 per cyclist or pedestrian at the main gate. Cash recommended." ),
				array( 'q' => 'Do you deliver bikes to Grayton Beach FL?', 'a' => "Yes, Peddlers delivers bikes to Grayton Beach rental properties. Contact us to arrange your delivery and confirm availability for your dates. Starting your 30A bicycle rental from your front door is the most convenient option for Grayton Beach guests." ),
				array( 'q' => 'What bikes work best for riding to Grayton Beach?', 'a' => "Multi-speed bikes are strongly recommended for the 58-minute daily rental ride between Peddlers and Grayton Beach. Cruiser bikes are ideal for shorter local rides once you arrive, between Grayton, Blue Mountain Beach (10 min west), and WaterColor (13 min east)." ),
				array( 'q' => 'What are the best 30A bike rides starting from Grayton Beach FL?', 'a' => "The best 30A bike rentals near Grayton Beach connect you to Blue Mountain Beach in 10 minutes west and WaterColor in 13 minutes east. For a longer beach vacation ride, Seaside is 15 minutes east and Gulf Place is 27 minutes west on the Gulf front." ),
				array( 'q' => 'Is Peddlers the top-rated bike rental near Grayton Beach FL?', 'a' => "Yes. Peddlers 30A is the top-rated bike rental for Grayton Beach with a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A. It is 11.5 miles east of Grayton Beach in the Seacrest Beach community on Florida's Panhandle Gulf Coast." ),
			),
		),

		'bike-rentals-alys-beach' => array(
			'title'        => 'Best Bike Rentals in Alys Beach | Peddlers 30A',
			'description'  => "Top-rated bike rental for Alys Beach, FL. Peddlers 30A is 0.9 miles east with 4.9 stars, 50+ bikes, and 15 years on 30A. Walk in or reserve today.",
			'h1'           => 'Best Bike Rentals in Alys Beach, Florida',
			'direct_answer'=> "Peddlers 30A is the top-rated bike rental for Alys Beach, 0.9 miles east at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Florida's Panhandle Gulf Coast. With a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A, Peddlers is the closest bicycle rental to Alys Beach.",
			'hero_lead'    => "Peddlers 30A is 5 minutes east of Alys Beach. Ride in past white walls, ironwork balconies, and the quietest stretch of 30A.",
			'trust_bar'    => array(
				array( 'heading' => 'FAMILY FIRST', 'sub' => 'All Ages Fit' ),
				array( 'heading' => 'CLOSEST RENTAL', 'sub' => '5 Min Away' ),
				array( 'heading' => 'LOCK INCLUDED', 'sub' => 'Every Rental' ),
				array( 'heading' => 'WALK-IN READY', 'sub' => 'Book or Walk In' ),
				array( 'heading' => 'DELIVERY AVAILABLE', 'sub' => 'Call to Arrange' ),
			),
			'rent_eyebrow' => 'RENT NEAR ALYS BEACH',
			'rent_title'   => 'Bikes for Every Alys Beach Rider',
			'local_eyebrow'=> 'ALYS BEACH',
			'local_title'  => 'The Sanctuary on 30A',
			'local_p1'     => "Alys Beach is 30A's most striking community, defined by brilliant-white Bermudan and Moorish architecture, ironwork balconies, and internal courtyards. Arriving from the east by bike, the iconic Butterling Towers mark the entrance to this private-feeling sanctuary on the Gulf.",
			'local_p2'     => "From Alys Beach, Peddlers 30A is 5 minutes east on Scenic Highway 30A. Rosemary Beach is also 4 minutes east. Inlet Beach Regional Access is 10 minutes east. Seagrove Beach and Seaside stretch west for a half-day Gulf front beach vacation ride.",
			'journey_title'=> "All of 30A Rides Out From Alys Beach",
			'journey_lead' => "From Alys Beach, Scenic Highway 30A stretches east and west across 24 miles of Florida Gulf Coast.",
			'journey_to'   => 'Alys Beach',
			'stats'        => array(
				array( 'value' => '2.0 Mi', 'label' => 'EAST' ),
				array( 'value' => '7.6 Mi', 'label' => 'WEST' ),
				array( 'value' => '24 Miles', 'label' => 'MILES OF 30A' ),
				array( 'value' => '16+', 'label' => 'DESTINATIONS' ),
			),
			'callout'      => "Peddlers 30A is 0.9 miles east of Alys Beach at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Scenic Highway 30A.",
			'pavilion_eyebrow' => 'YOUR HOME BASE',
			'pavilion_title'   => 'Where Every Alys Beach Ride Begins on 30A',
			'pavilion_lead'    => "Peddlers is 5 minutes east in Seacrest Beach. Kickstand Coffee before heading into Alys Beach, bikes at the door, and live music and cocktails waiting on your return.",
			'categories'   => array(
				array( 'num' => '01', 'label' => 'CLASSIC CRUISERS', 'title' => 'Glide Through Alys Beach', 'copy' => "Classic cruiser bikes suit the flat, paved paths through Alys Beach. Rosemary Beach is 4 minutes east and Inlet Beach is 10 minutes east." ),
				array( 'num' => '02', 'label' => 'MULTI-SPEED BIKES', 'title' => 'Ride Beyond Alys Beach', 'copy' => "Seagrove Beach is 32 minutes west and Seaside is 36. Multi-speed gearing makes the longer Gulf front runs from Alys Beach comfortable." ),
				array( 'num' => '03', 'label' => 'KIDS & FAMILY', 'title' => 'Explore the Courtyards', 'copy' => "Alys Beach's wide pedestrian paths are family-friendly cycling territory. Peddlers has kids' bikes, tag-alongs, and trailers for every rider." ),
				array( 'num' => '04', 'label' => 'SPECIALTY', 'title' => 'Go Further West or East', 'copy' => "Tandems and specialty bikes for Alys Beach riders wanting Prominence (13 min west) or Inlet Beach (10 min east) and beyond on 30A." ),
			),
			'why_eyebrow'  => 'THE SERVICE STANDARD',
			'why_title'    => 'Why Peddlers Is the Best Bike Rental Near Alys Beach',
			'why_cards'    => array(
				array( 'title' => '5 Minutes East', 'copy' => "No driving, no loading bikes. Peddlers is 5 minutes east of Alys Beach on 30A, and the coast is right out the door the moment you pick up your bike." ),
				array( 'title' => 'Inspected Every Day', 'copy' => "Every bike is checked before it goes out. The closest bicycle rental to Alys Beach is also the best-maintained fleet on Scenic Highway 30A." ),
				array( 'title' => 'Delivery Service Available', 'copy' => "Staying in Alys Beach and prefer to start from your rental property? Peddlers delivers. Contact us to arrange your delivery." ),
				array( 'title' => 'Local Advice Included', 'copy' => "Ask the team how to navigate Alys Beach by bike and which rental fits your group's plan for the day." ),
			),
			'closing_title'=> 'Your Alys Beach Ride Starts Here',
			'beaches_lead' => "From Alys Beach, Rosemary Beach and Inlet Beach are 4 and 10 minutes east. Prominence is 13 minutes west, with Seagrove and Seaside further along the Gulf front.",
			'beaches'      => array(
				array( 'badge' => '4 MIN RIDE', 'name' => 'Rosemary Beach', 'tag' => 'The Village on the Gulf', 'copy' => "Rosemary Beach is 4 minutes east of Alys Beach. Barrett Square, cobblestone lanes, gas-lit alleyways, and Amavida Coffee for a mid-ride stop.", 'pills' => array( '4 Min East', 'Town Square', 'Easy Ride' ), 'slug' => 'bike-rentals-rosemary-beach' ),
				array( 'badge' => '10 MIN RIDE', 'name' => 'Inlet Beach', 'tag' => 'Eastern End of 30A', 'copy' => "Inlet Beach is 10 minutes east of Alys Beach. The largest public beach access in Walton County, with boardwalk ramps, restrooms, and seasonal lifeguards.", 'pills' => array( '10 Min East', 'Public Access', 'Beach Access' ), 'slug' => 'bike-rentals-inlet-beach' ),
				array( 'badge' => '13 MIN RIDE', 'name' => 'Prominence', 'tag' => "30A's Most Lively Hub", 'copy' => "Prominence is 13 minutes west of Alys Beach. The Big Chill outdoor amphitheater has live music, a 25-foot LED screen, and food hall dining nightly.", 'pills' => array( '13 Min West', 'Live Events', 'Food & Drinks' ), 'slug' => 'bike-rentals-prominence' ),
				array( 'badge' => '32 MIN RIDE', 'name' => 'Seagrove Beach', 'tag' => 'Old Florida, Quiet Roads', 'copy' => "Seagrove Beach is 32 minutes west of Alys Beach. One of 30A's oldest communities, with oak canopy shade and a relaxed, local coastal feel.", 'pills' => array( '32 Min West', 'Local Feel', 'Beach Access' ), 'slug' => 'bike-rentals-seagrove-beach' ),
				array( 'badge' => '36 MIN RIDE', 'name' => 'Seaside', 'tag' => 'The Town Everyone Knows', 'copy' => "Seaside is 36 minutes west of Alys Beach. Lock up at the amphitheater, explore Central Square on foot, and stop at the Airstream food row.", 'pills' => array( '36 Min West', 'Town Square', 'Shops & Food' ), 'slug' => 'bike-rentals-seaside' ),
			),
			'testimonials_title' => 'Stories From Alys Beach',
			'faq_title'    => 'What to Know First',
			'faqs'         => array(
				array( 'q' => 'Where is Peddlers 30A located near Alys Beach?', 'a' => "Peddlers 30A is 0.9 miles east of Alys Beach at 10343 E County Hwy 30A, Inlet Beach, FL 32461 in the Seacrest Beach community. It is the closest bike rental in Alys Beach FL, 5 minutes east on Scenic Highway 30A." ),
				array( 'q' => 'Does Alys Beach have public beach access?', 'a' => "Alys Beach has private deeded walkovers for registered guests only. The nearest public access is Inlet Beach Regional Access, 2.0 miles east and 10 minutes by bike, with boardwalk ramps, restrooms, and seasonal lifeguards on the Gulf." ),
				array( 'q' => 'Can I walk in for a bike rental near Alys Beach?', 'a' => "Yes. Peddlers is 5 minutes east of Alys Beach and walk-ins are welcome. During peak summer weekends, the fleet fills quickly, so booking ahead is recommended. Weekdays and off-season, walk-in availability is generally good." ),
				array( 'q' => 'Do you deliver bikes to Alys Beach?', 'a' => "Yes, Peddlers delivers bikes to Alys Beach rental properties. Contact us to arrange your delivery and confirm availability for your dates. Starting your 30A bicycle rental from your front door is the easiest option." ),
				array( 'q' => 'What bikes work best for riding in and around Alys Beach?', 'a' => "Classic cruiser bikes are perfect for Alys Beach's flat pedestrian paths and short rides to Rosemary Beach (4 min east) and Inlet Beach (10 min east). For Seagrove or Seaside, a 7-speed daily rental bike is more comfortable." ),
				array( 'q' => 'What are the best 30A bike rides starting from Alys Beach?', 'a' => "The best bike rentals near Alys Beach FL lead to Rosemary Beach at 4 minutes east and Inlet Beach at 10 minutes east. For a longer day, Seagrove is 32 minutes west and Seaside is 36 minutes west on the Gulf front." ),
				array( 'q' => 'Is Peddlers the top-rated bike rental near Alys Beach?', 'a' => "Yes. Peddlers 30A is the closest and top-rated bike rental to Alys Beach with a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A. It is 0.9 miles east, 5 minutes away in Seacrest Beach." ),
			),
		),

		'bike-rentals-blue-mountain-beach' => array(
			'title'        => 'Best Bike Rentals Blue Mountain Beach | Peddlers 30A',
			'description'  => "Top-rated bike rental for Blue Mountain Beach FL. Peddlers 30A is 60 minutes east with 4.9 stars, 50+ bikes, and 15 years on 30A. Deliver to your door or reserve today.",
			'h1'           => 'Best Bike Rentals in Blue Mountain Beach, Florida',
			'direct_answer'=> "Peddlers 30A is the top-rated bike rental for Blue Mountain Beach, 12.5 miles east at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Florida's Panhandle Gulf Coast. With a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A, Peddlers is the closest dedicated bicycle rental for a Blue Mountain Beach FL beach vacation.",
			'hero_lead'    => "Peddlers 30A is 60 minutes east of Blue Mountain Beach. Reserve ahead or call. Delivery to Blue Mountain Beach FL is available.",
			'trust_bar'    => array(
				array( 'heading' => 'FAMILY FIRST', 'sub' => 'All Ages Fit' ),
				array( 'heading' => 'DELIVERY AVAILABLE', 'sub' => 'Call to Arrange' ),
				array( 'heading' => 'LOCK INCLUDED', 'sub' => 'Every Rental' ),
				array( 'heading' => 'WALK-IN READY', 'sub' => 'Book or Walk In' ),
				array( 'heading' => '60 MIN EAST', 'sub' => 'Pickup or Deliver' ),
			),
			'rent_eyebrow' => 'RENT NEAR BLUE MOUNTAIN BEACH',
			'rent_title'   => 'Bikes for Every Blue Mountain Rider',
			'local_eyebrow'=> 'BLUE MOUNTAIN BEACH',
			'local_title'  => "Florida's Highest Gulf Coast",
			'local_p1'     => "Blue Mountain Beach holds the highest elevation anywhere along Florida's Gulf Coast, approximately 64 feet above sea level. Early Spanish sailors named it Blue Mountain after the blue lupine flowers blanketing the high coastal bluffs they could see offshore from their ships.",
			'local_p2'     => "From Blue Mountain Beach, Peddlers 30A is 60 minutes east on Scenic Highway 30A. Gulf Place is 13 minutes west and Grayton Beach is 14 minutes east. Big Redfish Lake and Draper Lake sit directly behind the dunes, two of 30A's rare coastal dune lakes.",
			'journey_title'=> "30A Opens in Both Directions From Here",
			'journey_lead' => "From Blue Mountain Beach, 30A heads east toward Grayton Beach and west toward Gulf Place along Florida's Gulf Coast.",
			'journey_to'   => 'Blue Mountain Beach',
			'stats'        => array(
				array( 'value' => '3.0 Mi', 'label' => 'EAST' ),
				array( 'value' => '2.6 Mi', 'label' => 'WEST' ),
				array( 'value' => '24 Miles', 'label' => 'MILES OF 30A' ),
				array( 'value' => '16+', 'label' => 'DESTINATIONS' ),
			),
			'callout'      => "Peddlers 30A is 12.5 miles east of Blue Mountain Beach at 10343 E County Hwy 30A, Inlet Beach, FL 32461 on Scenic Highway 30A.",
			'pavilion_eyebrow' => 'YOUR HOME BASE',
			'pavilion_title'   => 'Where Every Blue Mountain Beach Ride Begins',
			'pavilion_lead'    => "Peddlers is 60 minutes east in Seacrest Beach. Reserve online or call ahead, and Kickstand Coffee is waiting when you arrive. Bikes are ready at the door for your full day at Blue Mountain Beach.",
			'categories'   => array(
				array( 'num' => '01', 'label' => 'CLASSIC CRUISERS', 'title' => 'Cruise Into Blue Mountain Beach', 'copy' => "Cruiser bikes handle the flat Gulf front path into Blue Mountain Beach. Gulf Place is 13 minutes west and Grayton Beach is 14 minutes east for a longer day." ),
				array( 'num' => '02', 'label' => 'MULTI-SPEED BIKES', 'title' => 'Ride the Full 60 Minutes', 'copy' => "The 60-minute ride from Peddlers to Blue Mountain Beach is a full-day Gulf front run. A 7-speed daily rental bike keeps the return trip comfortable on 30A." ),
				array( 'num' => '03', 'label' => 'KIDS & FAMILY', 'title' => 'Quiet Lanes and Dune Lake Paths', 'copy' => "Blue Mountain Beach's quiet residential side streets and dune lake paths are ideal for family riders. Peddlers has kids' bikes, tag-alongs, and trailers for every group." ),
				array( 'num' => '04', 'label' => 'SPECIALTY', 'title' => 'Reach Gulf Place or Grayton', 'copy' => "Tandems and specialty bikes for riders heading west to Gulf Place (13 min) or east to Grayton Beach (14 min) and WaterColor (19 min) on 30A." ),
			),
			'why_eyebrow'  => 'THE SERVICE STANDARD',
			'why_title'    => 'Why Peddlers Is the Best Bike Rental Near Blue Mountain Beach',
			'why_cards'    => array(
				array( 'title' => 'Delivery to Blue Mountain Beach', 'copy' => "Let Peddlers come to you. Delivery to Blue Mountain Beach FL rental properties is available. Contact us to arrange your bicycle rental drop-off and start the day from your front door." ),
				array( 'title' => 'Inspected Every Day', 'copy' => "Every bike goes out inspected and tuned. The best-maintained fleet on Scenic Highway 30A is 60 minutes east of Blue Mountain Beach at Peddlers Pavilion." ),
				array( 'title' => 'Delivery Service Available', 'copy' => "Prefer to start from your Blue Mountain Beach rental? Peddlers delivers. Contact us to arrange your delivery service to Blue Mountain Beach on 30A." ),
				array( 'title' => 'Local Advice Included', 'copy' => "Ask the team about the dune lake route through Big Redfish Lake, Blue Mountain Bakery for a mid-ride stop, and which bike fits your group's full day on 30A." ),
			),
			'closing_title'=> 'Your Blue Mountain Beach Ride Starts Here',
			'beaches_lead' => "From Blue Mountain Beach, Gulf Place is 13 minutes west and Grayton Beach is 14 minutes east. WaterColor is 19 minutes east and Seaside is 20 minutes east along the Gulf front.",
			'beaches'      => array(
				array( 'badge' => '13 MIN RIDE', 'name' => 'Gulf Place', 'tag' => 'The Heartbeat of Western 30A', 'copy' => "Gulf Place is 13 minutes west of Blue Mountain Beach. Shunk Gulley oyster bar, daily live music at the amphitheater, and Ed Walline Regional Beach Access right across 30A.", 'pills' => array( '13 Min West', 'Live Events', 'Beach Access' ), 'slug' => 'bike-rentals-gulf-place' ),
				array( 'badge' => '14 MIN RIDE', 'name' => 'Grayton Beach', 'tag' => 'Old Florida, Unchanged', 'copy' => "Grayton Beach is 14 minutes east of Blue Mountain Beach. The Red Bar for nightly jazz and live music, Grayton Beach State Park, and 30A's most bohemian village character.", 'pills' => array( '14 Min East', 'State Park', 'Live Music' ), 'slug' => 'bike-rentals-grayton-beach' ),
				array( 'badge' => '19 MIN RIDE', 'name' => 'WaterColor', 'tag' => 'Gulf Views and Timber Bridges', 'copy' => "WaterColor is 19 minutes east of Blue Mountain Beach. Cross the Western Lake timber bridge on the path and stop at WaterColor Town Center for a mid-ride break.", 'pills' => array( '19 Min East', 'Gulf Views', 'Resort Stop' ), 'slug' => 'bike-rentals-watercolor' ),
				array( 'badge' => '20 MIN RIDE', 'name' => 'Seaside', 'tag' => 'The Town Everyone Knows', 'copy' => "Seaside is 20 minutes east of Blue Mountain Beach. Lock up at Central Square perimeter racks, explore the amphitheater on foot, and stop at Airstream Row for lunch.", 'pills' => array( '20 Min East', 'Town Square', 'Shops & Food' ), 'slug' => 'bike-rentals-seaside' ),
				array( 'badge' => '~29 MIN RIDE', 'name' => 'Seagrove Beach', 'tag' => 'Old Florida, Quiet Roads', 'copy' => "Seagrove Beach is approximately 29 minutes east of Blue Mountain Beach via WaterColor. One of 30A's oldest communities, with maritime oak canopy and a quiet local feel.", 'pills' => array( '~29 Min East', 'Local Feel', 'Beach Access' ), 'slug' => 'bike-rentals-seagrove-beach' ),
			),
			'testimonials_title' => 'Stories From Blue Mountain Beach FL',
			'faq_title'    => 'What to Know First',
			'faqs'         => array(
				array( 'q' => 'Where is Peddlers 30A located near Blue Mountain Beach?', 'a' => "Peddlers 30A is 12.5 miles east of Blue Mountain Beach at 10343 E County Hwy 30A, Inlet Beach, FL 32461 in the Seacrest Beach community. It is the closest bike rental to Blue Mountain Beach FL, 60 minutes east on Scenic Highway 30A." ),
				array( 'q' => 'Why is it called Blue Mountain Beach in Florida?', 'a' => "Blue Mountain Beach was named by early Spanish sailors who saw the high coastal bluffs covered in blue lupine flowers from their ships offshore. At approximately 64 feet above sea level, it is the highest elevation point anywhere along Florida's Gulf Coast." ),
				array( 'q' => 'What are Big Redfish Lake and Draper Lake near Blue Mountain Beach?', 'a' => "Big Redfish Lake and Draper Lake are two of 30A's rare coastal dune lakes, located directly behind the Gulf beach dunes at Blue Mountain Beach. Both are accessible from 30A and visible from the paved cycling path through the community." ),
				array( 'q' => 'Do you deliver bikes to Blue Mountain Beach FL?', 'a' => "Yes, Peddlers delivers bikes to Blue Mountain Beach rental properties. Contact us to arrange your delivery and confirm availability for your dates. Starting your 30A bicycle rental from your front door is the most convenient option for Blue Mountain Beach guests." ),
				array( 'q' => 'What bikes work best for riding to Blue Mountain Beach?', 'a' => "Multi-speed bikes are strongly recommended for the 60-minute daily rental ride between Peddlers and Blue Mountain Beach. The elevation crest through the neighborhood is a gentle incline but is more noticeable on beach cruisers. Multi-speed gearing makes the full ride comfortable both ways." ),
				array( 'q' => 'What are the best 30A bike rides starting from Blue Mountain Beach FL?', 'a' => "The best 30A bike rentals near Blue Mountain Beach connect you to Gulf Place in 13 minutes west and Grayton Beach in 14 minutes east. WaterColor is 19 minutes east and Seaside is 20 minutes east. Blue Mountain Beach sits at the heart of western 30A's best cycling destinations." ),
				array( 'q' => 'Is Peddlers the top-rated bike rental near Blue Mountain Beach FL?', 'a' => "Yes. Peddlers 30A is the top-rated bike rental for Blue Mountain Beach with a 4.9-star Google rating, 50+ bikes, and 15 years on Scenic Highway 30A. It is 12.5 miles east of Blue Mountain Beach in the Seacrest Beach community on Florida's Panhandle Gulf Coast." ),
			),
		),

	);
}
